name: haptic_feedback

description: A Flutter plugin for haptic feedback. While it utilizes standard iOS haptics, it aims to emulate these same haptic patterns on Android for a consistent experience across platforms.
repository: https://github.com/nohli/haptic_feedback
issue_tracker: https://github.com/nohli/haptic_feedback/issues

topics:
  - haptic
  - feedback
  - haptics
  - vibration
  - plugin

version: 0.6.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.achim.haptic_feedback
        pluginClass: HapticFeedbackPlugin
      ios:
        pluginClass: HapticFeedbackPlugin
