name: Integration Tests (iOS)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration_test_ios:
    name: Integration test on iOS ${{ matrix.os-version }} - ${{ matrix.model }}
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os-version: ['18.6', '26.0']
        model: ['iPhone SE (3rd generation)', 'iPhone 16', 'iPhone 16 Pro Max']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Boot iOS simulator
        id: boot_simulator
        uses: futureware-tech/simulator-action@v4
        with:
          os_version: ${{ matrix.os-version }}
          model: ${{ matrix.model }}

      - name: Run integration tests on iOS
        run: |
          cd example
          flutter test integration_test -d "${{ steps.boot_simulator.outputs.udid }}"
